#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 5.0.{build}

# branches to build
branches:
  # blacklist
  except:
    - gh-pages

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

# scripts that run after cloning repository
install:
  - dotnet restore
  - ps: .\build\Install-Extra-Tools.ps1

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# to run your custom scripts instead of automatic MSBuild
build_script:
  - dotnet build -c %CONFIGURATION%

# environment variables
environment:
  codecov_token:
    secure: l7a3GWenI/cpY8OtMA684PnWojnc5sZnIGcfV70mpgmI+Vz7bBHqumUV5N77TdQ/
  
#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic tests
test_script:
  - dotnet test .\src\Vertica.Utilities.Tests\Vertica.Utilities.Tests.csproj -c %CONFIGURATION% --logger:trx;LogFileName=test-results.xml
  - ps: .\build\Upload-Test-Results.ps1

# scripts to run after tests
after_test:
  - dotnet pack .\src\Vertica.Utilities\Vertica.Utilities.csproj -c %CONFIGURATION%
  - ps: .\build\Generate-Coverage.ps1 -CoverageFile .\CoverageResult.xml

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:

  # pushing all *.nupkg files in build directory recursively
  - path: '**\*.nupkg'
    name: nupkg
  - path: 'CoverageResult.xml'
    name: coverage