#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 5.0.{build}

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

# branches to build
branches:
  # blacklist
  except:
    - gh-pages

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch
  - dotnet restore

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# to run your custom scripts instead of automatic MSBuild
build_script:
  - dotnet build -c %CONFIGURATION%
  
#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to run tests again only selected assemblies and/or categories
test:

# to run your custom scripts instead of automatic tests
test_script:
  - dotnet test .\src\Vertica.Utilities.Tests\Vertica.Utilities.Tests.csproj -c %CONFIGURATION% -l Appveyor

# scripts to run after tests
after_test:
  - dotnet pack .\src\Vertica.Utilities\Vertica.Utilities.csproj -c %CONFIGURATION%

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:

  # pushing all *.nupkg files in build directory recursively
  - path: '**\*.nupkg'